version: "3"

services:
  jenkins:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: jenkins
    environment:
      - JENKINS_JAVA_OPTS=-Djavax.net.ssl.trustStore=/var/jenkins_home/keystore/cacerts
    ports:
      - "127.0.0.1:8080:8080"
    volumes:
      - jenkins-home:/var/jenkins_home

volumes:
  jenkins-home:

